# Generated by Django 3.2.6 on 2021-10-25 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_posts_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likedBy',
        ),
        migrations.AddField(
            model_name='posts',
            name='likedBy',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
